GET http://localhost:5000/test/
###

POST http://localhost:5000/login/
Content-Type: application/json

{
    "username":"naidu",
    "password":"Batman@16"
}

###

POST http://localhost:5000/addstudent/
Content-Type: application/json

{
    "username":"revi",
    "fullname":"Sabbi Ravi",
    "email":"ravisabbi7036@gmail.com",
    "date_of_birth":"1999-05-27",
    "gender":"Male"
}

###

POST http://localhost:5000/sendmail/

###

GET http://localhost:5000/getstudents/

###

POST http://localhost:5000/sendmail/
Content-Type: application/json

{
    "to":"mohankumarkodi00@gmail.com",
    "link":"http://localhost:3000/quiz"
}
###


###
POST http://localhost:5000/studentscore/
Content-Type: application/json

{   
    "testId": "test_2",
    "email":"ravisabbi7036@gmail.com",
    "score":4,
    "testDate":"2023/02/02"
}
###


GET  http://localhost:5000/getscore/
Content-Type: application/json

{
    "email":"ravisabbi7036@gmail.com"
}
###